export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;
export const API_POSTBLOGS_POSTS_URL = `${API_BASE_URL}/${process.env.REACT_APP_API_POSTBLOGS_POSTS_URL}`;
export const API_POSTBLOGS_COMMENTS_URL = `${API_BASE_URL}/${process.env.REACT_APP_API_POSTBLOGS_COMMENTS_URL}`;